species:
    #aalo:
    #    fasta: data/transcriptomes/aalo.fasta
    #    url: ftp://ftp.ncbi.nlm.nih.gov/sra/wgs_aux/GE/TY/GETY01/GETY01.1.fsa_nt.gz
    #    name: "Alosa alosa"
    #btyr:
    #    fasta: data/transcriptomes/btyr.fasta
    #    name: "Brevoortia tyrannus"
    #spil:
    #    fasta: data/transcriptomes/spil.fasta
    #    name: "Sardina pilchardus"
    amex:
        fasta: data/transcriptomes/amex.fasta.1000
        url: ftp://ftp.ensembl.org/pub/release-85/fasta/astyanax_mexicanus/cdna/Astyanax_mexicanus.AstMex102.cdna.all.fa.gz
        name: "Astyanax mexicanus"
    gmor:
        fasta: data/transcriptomes/gmor.fasta.1000
        url: ftp://ftp.ensembl.org/pub/release-85/fasta/gadus_morhua/cdna/Gadus_morhua.gadMor1.cdna.all.fa.gz
        name: "Gadus morhua"
    #trur:
    #    fasta: data/transcriptomes/trur.fasta
    #    url: ftp://ftp.ensembl.org/pub/release-85/fasta/takifugu_rubripes/cdna/Takifugu_rubripes.FUGU4.cdna.all.fa.gz
    #    name: "Takifugu rubripes"
    orap:
        fasta: data/transcriptomes/orap.fasta.1000
        url: ftp://ftp.ensembl.org/pub/release-85/fasta/oryzias_latipes/cdna/Oryzias_latipes.MEDAKA1.cdna.all.fa.gz
        name: "Oryzias latipes"
    xmac:
        fasta: data/transcriptomes/xmac.fasta.1000
        url: ftp://ftp.ensembl.org/pub/release-85/fasta/xiphophorus_maculatus/cdna/Xiphophorus_maculatus.Xipmac4.4.2.cdna.all.fa.gz
        name: "Xiphophorus maculatus"
    #locu:
    #    fasta: data/transcriptomes/locu.fasta
    #    url: ftp://ftp.ensembl.org/pub/release-85/fasta/lepisosteus_oculatus/cdna/Lepisosteus_oculatus.LepOcu1.cdna.all.fa.gz
    #    name: "Lepisosteus oculatus"
    #gacu:
    #    fasta: data/transcriptomes/gacu.fasta
    #    url: ftp://ftp.ensembl.org/pub/release-85/fasta/gasterosteus_aculeatus/cdna/Gasterosteus_aculeatus.BROADS1.cdna.all.fa.gz
    #    name: "Gasterosteus aculeatus"
    #tnig:
    #    fasta: data/transcriptomes/tnig.fasta
    #    url: ftp://ftp.ensembl.org/pub/release-85/fasta/tetraodon_nigroviridis/cdna/Tetraodon_nigroviridis.TETRAODON8.cdna.all.fa.gz
    #    name: "Tetraodon nigroviridis"
    #onil:
    #    fasta: data/transcriptomes/onil.fasta
    #    url: ftp://ftp.ensembl.org/pub/release-85/fasta/oreochromis_niloticus/cdna/Oreochromis_niloticus.Orenil1.0.cdna.all.fa.gz
    #    name: "Oreochromis niloticus"
    drer:
        fasta: data/transcriptomes/drer.fasta.1000
        url: ftp://ftp.ensembl.org/pub/release-85/fasta/danio_rerio/cdna/Danio_rerio.GRCz10.cdna.all.fa.gz
        name: "Danio rerio"



databases:
    swissprot:
        url: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
    uniref90:
        url: ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz
    pfama:
        url: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam30.0/Pfam-A.hmm.gz



params:
    transdecoder:
        blastp:
            database: swissprot # or uniref90
            evalue: 1e-5
            max_target_seqs: 1
        hmmscan:
        predict:
    orthofinder:
        blastp_evalue: 0.001
        blastp_chunk_size: 100
        mcl_inflation: 1.5
    orthogroups:
        extract_orthogroups:
            minimum: 2
        fastcodeml:
            maximizer: 22
